config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root    'pages#home'

  resources :murals, :users, :images

  get     'foo'                        => 'users#foo'
  get     'artist/:id'                 => 'users#artist', :as => 'artist'
  get     'about'                      => 'pages#about'
  get     'contact'                    => 'pages#contact'
  get     'faq'                        => 'pages#faq'
  get     'logout'                     => 'sessions#destroy'
  get     'signup'                     => 'sessions#new'
  get     '/auth/:provider/callback'   => 'authentications#create'
  get     'data'                       => 'data#gallery'
  get     'groups'                     => 'data#groups'
  get     'upload'                     => 'data#mural_form'
  patch   'flagged/:id'                => 'images#flagged', :as => 'flagged'
  patch   'unflag/:id'                 => 'images#unflag', :as => 'unflag'
  get     'flagged_content'            => 'pages#flagged'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, dependent: :destroy
  has_many :images
  has_many :ownerships
  has_many :murals, through: :ownerships

  # if self.email?
  #   before_save { self.email = email.downcase}
  #   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #   validates :email, format: { with: VALID_EMAIL_REGEX },
  #             uniqueness: { case_sensitive: false }
  # end
  validates :first_name, presence: true

  mount_uploader :avatar, AvatarUploader


  def full_name
    [first_name, last_name].join(' ')
  end

  # dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def index
    @users = User.where(artist: true)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    set_user
    respond_to do |format|
      format.html do
        @murals = @user.murals
        @images = @user.images
      end
      format.json do
        if @user.artist?
          render json: MuralData.new.artist_data(@user.id)
        else
          render json: MuralData.new.profile_data(@user.id)
        end
      end
    end
  end

  def artist
    set_user
    respond_to do |format|
      format.html do
        @murals = Mural.joins(:ownerships).where({"ownerships.user_id" => @user.id}).uniq
      end
      format.json do
        render json: MuralData.new.artist_data(@user.id)
      end
    end
  end

  def foo
    #are you an artist page
  end

  def edit
    set_user
  end

  def update
    set_user
    if @user.update(user_params)
      redirect_to @user, notice: "Profile was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    set_user
    User.find(params[:id]).destroy
    redirect_to root_path, notice: "User was deleted successfully"
  end


  def unflagged_images(mural)
    mural.images.where(flagged: false)[0].source.url(:user_ablum)
  end

  def mural_has_unflagged_images(mural)
    mural.images.where(flagged: false).length == 0
  end

  helper_method :unflagged_images
  helper_method :mural_has_unflagged_images

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :twitter,
        :instagram,
        :avatar,
        :avatar_cache,
        :artist,
      )
    end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.haml
= form_for @user, html: {class: 'form-horizontal'} do |f|
  - if @user.errors.any?
    .alert.alert-danger
      - @user.errors.full_messages.each do |message|
        .text-center.no-decoration= message
  .col-md-6
    .form-group.col-md-offset-1
      = f.label :first_name, class: 'col-md-3'
      .col-md-6
        = f.text_field :first_name, class: 'form-control'

    .form-group.col-md-offset-1
      = f.label :last_name, class: 'col-md-3'
      .col-md-6
        = f.text_field :last_name, class: 'form-control'

    .form-group.col-md-offset-1
      = f.label :email, class: 'col-md-3'
      .col-md-6
        = f.email_field :email, class: 'form-control'

    .form-group.col-md-offset-1
      =f.label :twitter, class: 'col-md-3'
      .col-md-6
        =f.text_field :twitter, class: 'form-control'

    .form-group.col-md-offset-1
      =f.label :instagram, class: 'col-md-3'
      .col-md-6
        =f.text_field :instagram, class: 'form-control'

  .col-md-6
    .form-group
      .row
        = f.label :avatar, class: 'col-md-2'
        = f.file_field :avatar
        = f.hidden_field :avatar_cache
      .row
        = image_tag(@user.avatar_url(:thumb)) if @user.avatar?

  .actions
    = f.submit class: 'btn btn-primary'
    = link_to 'Delete Account', @user, method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete your account?"}

app/views/users/_new_artist_form.haml
= form_for @user, html: {class: 'form-horizontal'} do |f|
  - if @user.errors.any?
    .alert.alert-danger
      - @user.errors.full_messages.each do |message|
        .text-center.no-decoration= message

  .form-group.col-md-offset-1
    = image_tag(@user.avatar_url) if @user.avatar?
    = f.label :avatar, class: "col-md-1"
    = f.file_field :avatar, class: "btn col-md-3"
    = f.hidden_field :avatar_cache

  .form-group.col-md-offset-1
    = f.label :first_name, 'Name', class: "col-md-1"
    .col-md-3
      = f.text_field :first_name, class: "form-control"

  .form-group.col-md-offset-1
    = f.label :email, class: "col-md-1"
    .col-md-3
      = f.email_field :email, class: "form-control"

  .form-group
    .col-md-2.col-md-offset-1
      = f.check_box :artist, {checked: true}
      = f.label :artist

  .actions
    = f.submit 'Add Artist', class: "btn btn-primary col-md-offset-1"

app/views/users/artist.html.haml
.container-fluid
  .navbar-buffer
  .row
    .profile-map
    .gallery
      .profile-body
        .profile-left
          %h1.tube-sm.text-center= @user.first_name
          .social-links
            = link_to image_tag('https://s3.amazonaws.com/streetheart/twitter_icon.jpg'), 'http://www.twitter.com/' + @user.twitter, :target => '_blank' if @user.twitter?
            = link_to image_tag('https://s3.amazonaws.com/streetheart/instagram_icon.jpg'), 'http://www.instagram.com/' + @user.instagram, :target => '_blank' if @user.instagram?
          .profile-buttons
            - if current_user.nil?
            - elsif (@user.id == current_user.id) || (current_user.admin?)
              -# %p= link_to 'Are you an artist?', foo_path
              = link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-info'
              -# .btn.btn-default
              -#   %span.glyphicon.glyphicon-cog

        .profile-right
          - if @user.avatar?
            .profile-avatar
              = image_tag @user.avatar_url(:thumb)
          - else
            .profile-avatar
              = image_tag 'https://s3.amazonaws.com/streetheart/default_atom.png'
      .profile-murals
        - if @user.murals.any?
          - @murals.each do |mural|
            - unless mural_has_unflagged_images(mural)
              .gallery-mural
                = link_to mural_path(mural.id) do
                  = image_tag unflagged_images(mural), class: "galleryImg #{mural.id}"
- content_for(:js) do
  :javascript
    $(function(){
      MapFunctions.profileMap('#{artist_path(@user, format: :json)}');
    });

app/views/users/blah.html.haml
.container
  .col-md-6
    %h1= current_user
    %p If you're a local artist who has public work running in the streets you are eligble for an Artist Profile on Streetheart. Please submit an image of one of your public pieces.
    %p Presently Streetheart is in beta mode and currently will only be accepting murals as eligble content for submission. Check back soon though, as we are planning to cover the gamuet of public art works as the site gets fully up and running!
  .col-md-6
    = form_for @user, html: {class: 'form-horizontal'} do |f|
      - if @user.errors.any?
        .alert.alert-danger
          - @user.errors.full_messages.each do |message|
            .text-center.no-decoration= message

      .field.form-group.col-md-offset-1
        = image_tag(@user.avatar_url) if @user.avatar?
        = f.label :avatar, class: "col-md-1"
        = f.file_field :avatar, class: "btn col-md-3"
        = f.hidden_field :avatar_cache
      -# Currently set to update the user, not submit!!!
      .actions.form-group.col-md-offset-1
        = f.submit class: "btn btn-primary col-md-offset-1"

app/views/users/edit.html.haml
.container.navbar-buffer
  %h1 Edit Profile
  = render 'form'

app/views/users/index.html.haml
%h1.tube-sm.text-center Artist Profiles
.profile-container
  - @users.each do |user|
    .col-lg-2.profile-box
      = link_to user do
        .avatar
          = image_tag user.avatar.url(:thumb)
      .name-text
        %span
          = user.first_name
%br
.col-md-12
  %br
  -unless current_user.nil? || !current_user.admin?
    = link_to 'Add Artist', new_user_path, class: 'btn btn-info'

app/views/users/new.html.haml
.container
  %h1.text-center.tube-sm Add an artist
  %br
  = render 'new_artist_form'

app/views/users/show.html.haml
.container-fluid
  .navbar-buffer
  .row
    .profile-map
    .gallery
      .profile-body
        .profile-left
          %h1.tube-sm.text-center= @user.first_name
          .social-links
            = link_to image_tag('https://s3.amazonaws.com/streetheart/twitter_icon.jpg'), 'http://www.twitter.com/' + @user.twitter, :target => '_blank' if @user.twitter?
            = link_to image_tag('https://s3.amazonaws.com/streetheart/instagram_icon.jpg'), 'http://www.instagram.com/' + @user.instagram, :target => '_blank' if @user.instagram?
          .profile-buttons
            - if current_user.nil?
            - elsif (@user.id == current_user.id) || (current_user.admin?)
              -# %p= link_to 'Are you an artist?', foo_path
              = link_to 'Edit', edit_user_path(@user), class: 'btn btn-info'
              -# .btn.btn-default
              -#   %span.glyphicon.glyphicon-cog
            -if current_user.admin?
              = link_to 'Flagged', flagged_content_path, class: 'btn btn-warning'
        .profile-right
          - if @user.avatar?
            .profile-avatar
              = image_tag @user.avatar_url(:thumb)
          - else
            .profile-avatar
              = image_tag 'https://s3.amazonaws.com/streetheart/default_atom.png'
      .profile-murals
        - if @user.artist?
          -@murals.each do |mural|
            .gallery-mural
              = link_to mural_path(mural.id) do
                = image_tag mural.images[0].source.url(:user_ablum), class: "galleryImg #{mural.id}"

        - else
          -# - @user.images.any?
          - @images.each do |image|
            - unless image.flagged?
              .gallery-mural{class: "#{image.mural.id}"}
                = link_to image_path(image.id) do
                  = image_tag image.source.url(:user_ablum), class: "galleryImg #{image.mural.id}"
- content_for(:js) do
  :javascript
    $(function(){
      MapFunctions.profileMap('#{user_path(@user, format: :json)}');
    });