config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root    'pages#home'

  resources :murals, :users, :images

  get     'foo'                        => 'users#foo'
  get     'artist/:id'                 => 'users#artist', :as => 'artist'
  get     'about'                      => 'pages#about'
  get     'contact'                    => 'pages#contact'
  get     'faq'                        => 'pages#faq'
  get     'logout'                     => 'sessions#destroy'
  get     'signup'                     => 'sessions#new'
  get     '/auth/:provider/callback'   => 'authentications#create'
  get     'data'                       => 'data#gallery'
  get     'groups'                     => 'data#groups'
  get     'upload'                     => 'data#mural_form'
  patch   'flagged/:id'                => 'images#flagged', :as => 'flagged'
  patch   'unflag/:id'                 => 'images#unflag', :as => 'unflag'
  get     'flagged_content'            => 'pages#flagged'
end

app/views/pages/about.html.haml
.container
  %h1.tube-lg.text-center What is Streetheart all about?
.container.push
  %br
  %p
    Streetheart began after a move back to Denver and feeling like we were living in our cars. Surely there was something worth getting out and walking for. Street art had been something enjoyable about living in places like Chicago and New York, so we set out to find the art around Denver. Initially, it was just about discovering the pockets of urbanism in a more spread out city, but we soon realized that street art could bring so much more to our community.
  %p
    @DenverStreetart, our Instagram, was the first part of our project, where we took to the streets, captured bits of the myriad murals around town, tagging each with a location and our best to get the artists as well. It was our hope that people viewing our pictures would be motivated to go see the pieces they really liked in person. Anything to get them out and connecting with the community in a different way, or at least noticing what was already right in front of them, appreciating the art and the people who created it.
  %p
    The art is so much more than just beautiful imagery. It's also symbol of community. Just like we want people out engaging with the art in person, the art in turn gets those people out and engaging in their community. The more art there is, the more people we’ll see on the street, connecting with each other, with local business and with the arts. Our project is now angling toward connecting open walls with willing artists, in the hopes that even more places throughout Denver will become public art exhibits, drawing the community together.
.photoright

app/views/pages/contact.html.haml
.jumbotron
  %img{:alt => "Denver Street Art molina barrios", :src => "https://s3.amazonaws.com/streetheart/denver+street+art+jaime+molina+pedro+barrios.jpg"}
%p.photocred Street art by Jaime Molina, Pedro Barrios  Joseph Martinez
.container.text-center
  = link_to image_tag('https://s3.amazonaws.com/streetheart/twitter.png'), 'http://www.twitter.com/denverstreetart', :target => '_blank'
  = link_to image_tag('https://s3.amazonaws.com/streetheart/instagram.png'), 'http://www.instagram.com/denverstreetart', :target => '_blank'
  -# = link_to image_tag('https://s3.amazonaws.com/streetheart/email.png'), 'mailto:adam@denverstreetheart.com', :target => '_blank'

app/views/pages/faq.html.haml
.container
  %h1.tube-lg.text-center Frequently Asked Questions
.container.push
  %br
  %p
    How can I get Streetheart for my city?
  %p
    Why does Streetheart want to use my location?
  %p
    I am an artist with public work up in this city. How do I get listed?
  %p
    Why are there only options to sign in with Twitter and Instagram?

  -# Have a text_area submission field for users to ask a question not covered
  -# in the listed FAQs
  -# Once the list gets long enough there should be page jumps linking to questions

app/views/pages/flagged.html.haml
%section
  .container-fluid
    .row
      .col-md-12
        .flagged_page
          .row
            - @images.each do |image|
              .col-md-4.gallery-mural
                = image_tag image.source.url(:user_ablum)
                %br
                .flag-buttons
                  = link_to 'Unflag', unflag_path(image.id), class: 'btn btn-warning', data: {confirm: "Are you sure you want to PUBLISH this image?"}, method: :patch, action: :unflag
                  = link_to 'Delete', image, class: 'btn btn-danger', data: {confirm: "Are you sure you want to DELETE this image?"}, method: :delete
                  %hr

app/views/pages/home.html.haml
%section
  .jumbotron
    = image_tag('https://s3.amazonaws.com/streetheart/denver+street+art+hero.jpg')
  .photocred Street art by Daniel Chavez  Keno Gonzales | Eddie Huang, Michael Kraus  Jacobo Gonzalez
  .news
    .news-item
      %h2 Latest News
      %p Applications for Denver Public Art's Urban Art Fund close on March 31st. Be sure to head over to their site and get your application in ASAP. Grants range from $500-$5,000 for street art projects!
      %p
        %a.btn.btn-default{:href => "http://artsandvenuesdenver.com/public-art/urban-arts-fund/", :role => "button", :target => "_blank"} View details »
    .news-item
      %h2 Need a wall?
      %p We’re partnering with business and property owners around town to help artists find locations to paint. Artists, you probably don’t want to spend your time hunting down walls and cozying up to business owners. We want to make that process easier, so you can get out and create more art around Denver!
    .news-item
      %h2 Want a mural?
      %p Get in touch with us if you’re interested in having an artist paint a mural on your property. Street art will draw attention to your business, and it's a great way to beautify your community. We’re working with artists and alongside the city to make the process of matching artists to your businesses easier every day.
%a{name: 'map'}
%a.map
%section.profile
  .gallery-map
  .gallery
    - @murals.each do |mural|
      - unless mural.images[0].flagged?
        .gallery-mural
          = link_to mural_path(mural.id) do
            = image_tag mural.images[0].source.url(:user_ablum), class: "galleryImg #{mural.id}"
%a{name: 'artists'}
%a.artists
%section
  %h1.tube-sm.text-center Artist Profiles
  .artist-profiles
    - @users.each do |user|
      .profile-box
        = link_to artist_path(user.id) do
          .avatar
            = image_tag user.avatar.url(:thumb)
        .name-text
          %span
            = user.first_name
            = user.last_name
    -unless current_user.nil? || !current_user.admin?
      = link_to 'Add Artist', new_user_path, class: 'btn btn-info'

- content_for(:js) do
  :javascript
    $(function(){
      MapFunctions.homeMap();
    });