config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root    'pages#home'

  resources :murals, :users, :images

  get     'foo'                        => 'users#foo'
  get     'artist/:id'                 => 'users#artist', :as => 'artist'
  get     'about'                      => 'pages#about'
  get     'contact'                    => 'pages#contact'
  get     'faq'                        => 'pages#faq'
  get     'logout'                     => 'sessions#destroy'
  get     'signup'                     => 'sessions#new'
  get     '/auth/:provider/callback'   => 'authentications#create'
  get     'data'                       => 'data#gallery'
  get     'groups'                     => 'data#groups'
  get     'upload'                     => 'data#mural_form'
  patch   'flagged/:id'                => 'images#flagged', :as => 'flagged'
  patch   'unflag/:id'                 => 'images#unflag', :as => 'unflag'
  get     'flagged_content'            => 'pages#flagged'
end

app/models/mural.rb
class Mural < ActiveRecord::Base
  has_many :ownerships
  has_many :images
  has_many :users, through: :ownership
  # default_scope -> { order('created_at DESC') }
  # validates :image, :latitude, :longitude, presence: true

  # Original:
  # Mural.where(latitude: minlat..maxlat).where(longitude: minlng..maxlng)

  # Define named scopes in the model to use later:
  # scope :between_latitudes, ->(min_lat, max_lat) { where(latitude: min_lat..max_lat)}
  # scope :between_longitudes, ->(min_lng, max_lng) { where(longitudes: min_lng..max_lng)}

  # The refactored original query:
  # Mural.between_latitudes(minlat, maxlat).between_longitudes(minlng, maxlng)

  def as_gallery_data
    map_set(images[0].source.url(:thumb))
  end

  def as_artist_data
    map_set(images[0].source.url(:thumb))
  end

  def as_show_data
    map_set[:geometry].delete(:image)
  end

  def to_hash
    mural = {}
    mural[:latitude] = latitude
    mural[:longitude] = longitude
    # doesnt account for multiple ownerships
    mural[:artist_id] = ownerships[0].user_id
    mural[:mural_id] = id
    mural[:image] = images[0].source.user_ablum.url
    mural
  end

private

  def map_set(*image)
    { type: 'Feature',
      geometry: {
        type: 'Point',
        id: id,
        coordinates: [longitude, latitude],
        image: image
     }
   }
  end
end

app/controllers/murals_controller.rb
class MuralsController < ApplicationController
  # before_action :logged_in_user, only: [:create, :destroy]

  def new
    if current_user
      @image = current_user.images.build
      @image.ownerships.build

      @mural = current_user.murals.build
      @mural.ownerships.build
      @mural.images.build
    else
      redirect_to :root, notice: 'You must be logged in to add murals to the map.'
    end
  end

  def create
    @mural = current_user.murals.new(mural_params)
    if @mural.save
      redirect_to :root
    else
      render :new
    end
  end

  def show
    @mural = Mural.find(params[:id])
    @images = @mural.images.where.not(flagged: true)
    @artist = User.find(@mural.ownerships[0].user_id)
    respond_to do |format|
      format.html do
        @mural
      end
      format.json do
        render json: MuralData.new.show_data(params[:id])
      end
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      redirect_to :root
    else
      render :edit
    end
  end


  private

    def mural_params
      params.require(:mural).permit(
        :longitude,
        :latitude,
        images_attributes: [:user_id, :source, :source_cache ],
        ownerships_attributes: [:user_id]
      )
    end

    def image_params
      params.require(:mural).permit(
        images_attributes: [:user_id, :source, :source_cache ],
      )
    end

end

app/views/murals/_upload_form.html.haml
.col-md-12
  = form_for @image do |f|

    .form-group.row.hide-me
      .col-md-12.ownership_form
        = f.fields_for :ownerships do |owner|
          = owner.hidden_field :mural_id, id: 'owner-mural-id'
          = owner.label "Artist"
          = owner.collection_select(:user_id, User.where(artist: true), :id, :full_name, { include_blank: "Pick an artist" }, {class: 'form-control'})

    .form-group.row
      .col-md-12.murals_form
        = f.fields_for :murals do |mural|
          = mural.hidden_field :latitude, id: 'lat'
          = mural.hidden_field :longitude, id: 'long'

    %div.col-md-12.well
      .form-group
        .col-md-6.col-md-offset-1.images_form
          = f.hidden_field :mural_id, id: 'image-mural-id'
          = f.hidden_field :user_id, value: current_user.id
          = f.label :source, 'Add Image'
          = f.file_field :source
          = f.file_field :source_cache, class: 'hidden'

      .form-group
        .col-md-5
          =f.submit 'Upload Mural', class: 'btn btn-primary upload-btn'

app/views/murals/edit.html.haml
.container.navbar-buffer
  %h1.text-center Edit Mural
  .text-center
    = image_tag @image.source
  = link_to 'Delete', mural_path, class: 'btn btn-danger', method: :delete

app/views/murals/index.html.haml
.col-md-12
  .row
    .col-md-7#gallery-map.gallery-map
    .gallery
      .scrollable
        -@murals.each do |mural|
          .col-md-4.gallery-mural
            = link_to mural do
              = image_tag mural.image.url(:user_ablum), class: "mapPin #{mural.id}"
- content_for(:js) do
  :javascript
    $(function(){
      MapFunctions.galleryMap();
    });

app/views/murals/new.html.haml
.container-fluid
  .navbar-buffer
  %h1.text-center Add some street art!
  .row
    .col-md-7.new-map
    .col-md-5
      .upload-form= render 'upload_form'
      .mural-list.text-center
        %h4 Mural already listed? Add it to the collection...
        .near-by

- content_for(:js) do
  :javascript
    $(function(){
      MapFunctions.dropMap();
    });

app/views/murals/show.html.haml
.container-fluid.navbar-buffer
  .artist-show-title.tube-lg.text-center
    %h1= link_to @artist.first_name, artist_path(@artist)
  .row
    .col-md-9.text-center
      - @images.each do |image|
        .gallery-mural
          = link_to image_path(image.id) do
            = image_tag image.source.url(:thumb)
            .flagged
              %span
                = link_to flagged_path(image.id), data: {confirm: "Are you sure you want to report this image for abusive content?"}, method: :patch, action: :flagged do
                  %i.fa.fa-ban.fa-2x
    .col-md-3
      .show-map
      %br
      = link_to image_tag('https://s3.amazonaws.com/streetheart/twitter_icon.jpg'), 'http://www.twitter.com/' + @artist.twitter, :target => '_blank' if @artist.twitter?
      = link_to image_tag('https://s3.amazonaws.com/streetheart/instagram_icon.jpg'), 'http://www.instagram.com/' + @artist.instagram, :target => '_blank' if @artist.instagram?

      %br
      - if current_user.nil?
      - elsif @artist.id == current_user.id || current_user.admin?
        = link_to 'Edit', edit_mural_path, class: 'btn btn-primary'
- content_for(:js) do
  :javascript
    $(function() {
      MapFunctions.showMap('#{mural_path(@mural, format: :json)}');
    });