config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root    'pages#home'

  resources :murals, :users, :images

  get     'foo'                        => 'users#foo'
  get     'artist/:id'                 => 'users#artist', :as => 'artist'
  get     'about'                      => 'pages#about'
  get     'contact'                    => 'pages#contact'
  get     'faq'                        => 'pages#faq'
  get     'logout'                     => 'sessions#destroy'
  get     'signup'                     => 'sessions#new'
  get     '/auth/:provider/callback'   => 'authentications#create'
  get     'data'                       => 'data#gallery'
  get     'groups'                     => 'data#groups'
  get     'upload'                     => 'data#mural_form'
  patch   'flagged/:id'                => 'images#flagged', :as => 'flagged'
  patch   'unflag/:id'                 => 'images#unflag', :as => 'unflag'
  get     'flagged_content'            => 'pages#flagged'
end

app/views/layouts/_footer.html.haml
%hr
  %footer
    %script{:src => "https://maps.googleapis.com/maps/api/js?libraries=geometry&key=AIzaSyCM2cZI7nhe7pImTKAMaZAuyjs2jfZx4pI&sensor=true", :type => "text/javascript"}
    = javascript_include_tag 'application'
    = content_for(:js)
    .nav.navbar-nav
      = link_unless_on_own_page(about_path, 'About')
      = link_unless_on_own_page(contact_path, 'Contact')
      = link_unless_on_own_page(faq_path, 'FAQs')
    %p.navbar-right ©Denver Streetheart 2014

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} Streetheartβeta
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      = link_to 'Upload Image', new_image_path, class: 'btn btn-info navbar-btn pull-right'
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Map', root_path(anchor: "map")
        %li
          = link_to 'Artists', root_path(anchor: 'artists')
        %li.dropdown
          -if current_user
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.first_name.capitalize
              %b.caret
            %ul.dropdown-menu{:role => "menu"}
              %li= link_to "Profile", current_user
              %li.divider
              %li= link_to 'Log out', logout_path
          -else
            %a.dropdown-toggle{"aria-expandeed" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Login | Signup
              %b.caret
            %ul.dropdown-menu{:role => "menu"}
              %li.auth-btns
                = link_to "/auth/twitter", class: "btn btn-info" do
                  = image_tag('https://s3.amazonaws.com/streetheart/tweet-wht.png')
              %li.auth-btns
                = link_to "/auth/instagram", class: "btn btn-warning" do
                  = image_tag('https://s3.amazonaws.com/streetheart/insta-wht.png')
- if flash[:notice]
  %p.alert.alert-danger.text-center.col-sm-12= flash[:notice]

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Streetheart
    = stylesheet_link_tag    'application', media: 'all'
    %meta{:content => "width=device-width,initial-scale=1.0", :name => "viewport"}
    %link{:rel=> :stylesheet, :href=> "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"}
    = csrf_meta_tags
    = favicon_link_tag '/hearticon.png'
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'